### ISSUE TITLE
CommonTabLayout和SlidingTabLayout套用的时候 tab切换出现问题

### ISSUE THREAD

**Issue by hong4cong** [H07000223/FlycoTabLayout#1]
![device-2015-11-17-183446](https://cloud.githubusercontent.com/assets/8746352/11209100/0c988a7a-8d5a-11e5-9080-8d601a289d7d.png)
上面是正常情况下的切换
![device-2015-11-17-183531](https://cloud.githubusercontent.com/assets/8746352/11209111/2142fa82-8d5a-11e5-8913-5f03c655100b.png)
异常情况如上图

**Comment by hong4cong** [comment]
![4feaae61-fd81-444e-b20c-e2d1bf8bb11a](https://cloud.githubusercontent.com/assets/8746352/11209205/bcdc5290-8d5a-11e5-8c0f-7536b1d75e6c.png)
补充

**Comment by H07000223** [comment]
Fragment嵌套问题
在fragment里还有fragment的话,里面要用getChildFragmentManager()来获取fragmentManager
