### ISSUE TITLE
underline 和 indicator的区别

### ISSUE THREAD

**Issue by blindfate** [H07000223/FlycoTabLayout#10]
对于CommonTabLayout的两个属性不是很清楚它们的区别，能否解释下，谢谢！
tl_indicator_color 和 tl_underline_color
tl_indicator_height 和 tl_underline_height

**Comment by invinjun** [comment]
试试就知道了
2016年2月25日 11:48，"blindfate" <notifications@github.com>写道：

**Comment by H07000223** [comment]
![6e811027-807d-40ca-b554-4ef928a108b4](https://cloud.githubusercontent.com/assets/3666423/13322053/89dc80f2-dc0d-11e5-8cce-a4d826c1d5b5.jpeg)
