### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by szitguy** [H07000223/FlycoTabLayout#101]
1.proguard配置有没有？
2.`重要`我只用到了CommonTabLayout控件，能否将其他Layout剔除掉？

**Comment by H07000223** [comment]
1.可以单独拷出来~
proguad的话,如果项目中有类似全局配置自定义控件不被混淆的话，就不需要；
没有的话，也可以单独 -keep class 路径名. CommonTabLayout {*;}

2.引用库的话
-keep class com.flyco.tablayout.** {*;}
