### ISSUE TITLE
冲突问题

### ISSUE THREAD

**Issue by wangguifa** [H07000223/FlycoTabLayout#111]
请问使用CommonTabLayout和com.jcodecraeer.xrecyclerview.XRecyclerView和com.youth.banner.Banner。当三个同时出现时，XRecyclerView下拉刷新就不能用了，当Banner不存在时，刷新就可以使用，请问怎么解决呢？

**Comment by H07000223** [comment]
这个不是本库造成的问题~应该去XRecyclerView提issue
