### ISSUE TITLE
已解决:SegmentTabLayout segmentTab = new SegmentTabLayout(this);  on a null object reference

### ISSUE THREAD

**Issue by LonelyMushroom** [H07000223/FlycoTabLayout#112]
>  SegmentTabLayout segmentTab = new SegmentTabLayout(this);

Attempt to invoke interface method 'java.lang.String android.util.AttributeSet.getAttributeValue(java.lang.String, java.lang.String)' on a null object reference

原因是

> //get layout_height
        String height = attrs.getAttributeValue("http://schemas.android.com/apk/res/android", "layout_height");

想问问作者我该如何用代码new出来

**Comment by H07000223** [comment]
老实说没new过😂，你确实需要的话可以专门弄个xml放SegmentTabLayout，在合适的情况下inflate，加入到希望的父控件中~

**Comment by LonelyMushroom** [comment]
@H07000223 嗯嗯 我就是按照你那样弄的

> <?xml version="1.0" encoding="utf-8"?>
<com.flyco.tablayout.SegmentTabLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tl="http://schemas.android.com/apk/res-auto"
    android:id="@+id/tl_1"
    android:layout_width="wrap_content"
    android:layout_height="32dp"
    tl:tl_bar_color="@color/orange_style"
    tl:tl_indicator_color="@color/white"
    tl:tl_indicator_corner_radius="5dp"
    tl:tl_tab_padding="20dp"

    tl:tl_indicator_margin_bottom="0dp"
    tl:tl_indicator_margin_left="0dp"
    tl:tl_indicator_margin_right="0dp"
    tl:tl_indicator_margin_top="0dp"

    tl:tl_textSelectColor="@color/orange_style"

    android:layout_centerVertical="true"
    android:layout_centerHorizontal="true"

    tl:tl_tab_space_equal="true"
    tl:tl_indicator_anim_enable="false"
    tl:tl_indicator_bounce_enable="false"

    tl:tl_divider_width="0dp"
    />

> SegmentTabLayout tab = (SegmentTabLayout) LayoutInflater.from(context).inflate(R.layout.tablayout_segment_qq, rlCenter, false);
        rlCenter.addView(tab);
        String[] titles = initialData(segmentLists);
        tab.setTabData(titles);
        tab.setCurrentTab(index);
        tab.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelect(int position) {
                webView.callHandler("Click Segment Item", String.valueOf(position), new CallBackFunction() {
                    @Override
                    public void onCallBack(String data) {

                    }
                });
            }

            @Override
            public void onTabReselect(int position) {

            }
        });

这样就可以了,布局也没问题,很棒.但是有个问题就是我调用setCurrentTab这个方法指定选中哪个标签时,不会触动我之前设置的监听,比如说

> controller.addTabItemClickListener(new OnTabItemSelectListener() {
            @Override
            public void onSelected(int position, Object tag) {
//                showHideFragment(mFragments[position], mFragments[mCurrentPosition]);
                showHideFG(mFragments[position], mFragments[mCurrentPosition]);
                mCurrentPosition = position;
            }

            @Override
            public void onRepeatClick(int index, Object tag) {
                return;
            }
        });

> controller.setSelect(mCurrentPosition);

我下面这句setSelect就是调用onSelected方法,你觉得有必要这样做吗?

**Comment by LonelyMushroom** [comment]
我重新发个提问吧,这个代码贴的太丑了..
