### ISSUE TITLE
最好使用support v13，否则不能添加perferencefragment

### ISSUE THREAD

**Issue by netstu** [H07000223/FlycoTabLayout#114]
最好使用support v13， Fragment使用android.app.Fragment

import android.support.v13.app.FragmentPagerAdapter;

FragmentManager 使用 android.app.FragmetManager

getSupportFragmentManager 改为 getFragmentManager

我改了好久才可以用

**Comment by H07000223** [comment]
Fragment，并不是必须的参数~你可以使用不带Fragment构造方法~Fragment的管理可以单独自己写
