### ISSUE TITLE
希望升级buildToolsVersion

### ISSUE THREAD

**Issue by jlkm2010** [H07000223/FlycoTabLayout#115]
希望升级buildToolsVersion和compileSdkVersion

**Comment by H07000223** [comment]
会报什么问题嘛

**Comment by jlkm2010** [comment]
- 低版本的buildTools中aapt在64位linux环境中需要安装32位依赖，使用jenkins打包时需要解决这个问题
- 目前新版本buildTools不需要安装依赖
- 我使用的这个项目的源码，没有直接使用gradle依赖
- 问题不是很紧急，我可以自行修改buildToolsVersion
- 谢谢

**Comment by H07000223** [comment]
ok~我找个时间改下😂

**Comment by H07000223** [comment]
更新到2.1.2，你试下还有问题嘛

**Comment by jlkm2010** [comment]
非常感谢🙏
