### ISSUE TITLE
红点显示在左上角

### ISSUE THREAD

**Issue by Liuyaowu** [H07000223/FlycoTabLayout#116]
Tab只有两个，我在在布局中设置：tl:tl_tab_space_equal="true"，红点显示在了左上角，去掉就正常了

**Comment by H07000223** [comment]
参考[#issue24](https://github.com/H07000223/FlycoTabLayout/issues/24)
参考[#issue4](https://github.com/H07000223/FlycoTabLayout/issues/4)
