### ISSUE TITLE
Problem with Indicator

### ISSUE THREAD

**Issue by Hamid95** [H07000223/FlycoTabLayout#12]
hi.
I have a confusing problem when I use block indicator somthing like this:

code:
---------------------------------------------------
tl:tl_indicator_corner_radius="0dp"
tl:tl_indicator_margin_bottom="0dp"
tl:tl_indicator_margin_left="0dp"
tl:tl_indicator_margin_right="0dp"
tl:tl_indicator_margin_top="0dp"
tl:tl_indicator_style="BLOCK"
----------------------------------------------------

when I use this code in most android devices the indicator do not show.
(in emulator works perfectly)

plz help me!

thank you so much...

**Comment by H07000223** [comment]
Show me your code and give me more detail : such as my lib version , android sdk version and etc.

I have tried all my genymotion devices and my phone(HUAWEI PE-TL20 Android 4.4.2, API 19) 
and it works ok. So I do not know what's wrong. You can first try it in my github demo.
![ed244a94-5a9b-4404-a4b3-c3ce23ca0174](https://cloud.githubusercontent.com/assets/3666423/13623597/aa9e1056-e5e2-11e5-8870-943f1e4a7660.png)

**Comment by Hamid95** [comment]
it is my xml code:

`<com.flyco.tablayout.CommonTabLayout xmlns:tl="http://schemas.android.com/apk/res-auto"
        android:id="@+id/tl_main"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:layout_alignParentBottom="true"
        android:background="#1E76B0"
        tl:tl_indicator_color="#1168a1"
        tl:tl_indicator_corner_radius="0dp"
        tl:tl_indicator_margin_bottom="0dp"
        tl:tl_indicator_margin_left="0dp"
        tl:tl_indicator_margin_right="0dp"
        tl:tl_indicator_margin_top="0dp"
        tl:tl_indicator_style="BLOCK"
        tl:tl_textBold="true"
        tl:tl_textSelectColor="#FFFFFF"
        tl:tl_textUnselectColor="#60AFE4"
        tl:tl_textsize="12sp" />`

-> your lib version is "1.5.0"
->my minSdkVersion 8
->my targetSdkVersion 23


it works perfectly in all my genymotion devices but in my phone with android 4.1.2
and some other phone and tablets (even android 5) it works bad. and the indicator do not show

**Comment by H07000223** [comment]
You can have a try first as follow:
1.try to use the lastest lib version and github demo for test
2.try to use LinearLayout weight instead of layout_alignParentBottom(maybe caused by RelativeLayout, I am not sure)

**Comment by ydmmocoo** [comment]
使用setCurrentTab()方法，显示器好像不会显示了.点击的就会显示并移动

**Comment by ydmmocoo** [comment]
原来是自己库版本太旧了，更新到最新，问题解决了

**Comment by H07000223** [comment]
问题解决,就好~
