### ISSUE TITLE
SlidingTabLayout滑动必须依赖于ViewPager的滑动吗？可否只滑动Tab中的Indicator?

### ISSUE THREAD

**Issue by dinglin87** [H07000223/FlycoTabLayout#123]
大神好！
 需求背景：有很多个Tab要展示，超出屏幕展示范围，发现只有SlidingTabLayout支持这种，所以选择SlidingTabLayout。
问题： SlidingTabLayout依赖于ViewPager，但我们的需求是切换时不展示动画，所以ViewPager切换时调viewPager.setCurrentItem(item, false)函数（第2个参数为false），发现这样调用之后，Indicator也没有了滑动效果，SlidingTabLayout滑动效果必须依赖于ViewPager的滑动吗？这种情况下，如何让Indicator具备滑动效果？

**Comment by dinglin87** [comment]
谢谢大神！

**Comment by ldqmaybe** [comment]
求同

**Comment by H07000223** [comment]
1.设计就是如此~ SlidingTabLayout中的动画，是依赖onPageScrolled方法中偏移量
![image](https://cloud.githubusercontent.com/assets/3666423/23205502/0b0db7a6-f925-11e6-805b-c2f8fb375c58.png)

2.可以尝试HorizontalScrollView嵌套CommonTabLayout实现，只是点击某个tab没有滚动居中效果

**Comment by dinglin87** [comment]
好的。谢谢！

**Comment by gzpaiwxc** [comment]
感谢 , 问题解决
