### ISSUE TITLE
CommonTabLayout预加载Fragment?

### ISSUE THREAD

**Issue by dinglin87** [H07000223/FlycoTabLayout#126]
大神好：

        CommonTabLayout 下有三个Tab页：Tab1、Tab2、Tab3，我从Tab1滑动到Tab2时发现会提前预加载Tab3，是本来就这么设计的吗？还是我的代码有问题？如果本来就这么设计的，如果关闭预加载？谢谢大神！

**Comment by H07000223** [comment]
是否预加载可以自己控制~通过Fragment的setUserVisibleHint方法

**Comment by dinglin87** [comment]
好的。多谢！
