### ISSUE TITLE
CommonTableLayout设置为5个之后的MsgView问题.

### ISSUE THREAD

**Issue by twisty1988** [H07000223/FlycoTabLayout#13]
<img width="574" alt="2016-03-10 13 54 01" src="https://cloud.githubusercontent.com/assets/3094380/13660725/97f416e0-e6c7-11e5-8b7d-c61f071ff5e7.png">

这样MsgView就显示不下那么多数字了,但是看MsgView的左右Padding都还有位置,要如何设置才能让他们显示下来呢.

**Comment by H07000223** [comment]
1.UnreadMsgUtils是一个辅助展示类~你可以根据自身需求仿造一个工具类.
2.不要直接使用TabLayout的showMsg方法,而是通过TabLayout获取MsgView自行处理(用自己写的工具类)

**Comment by twisty1988** [comment]
👏👏👏非常感谢.解决了.
