### ISSUE TITLE
老大问个问题

### ISSUE THREAD

**Issue by k354250377** [H07000223/FlycoTabLayout#132]
CommonTabLayout这个控件 如果不想要下面的字 把它隐藏了还是会占位置 请问有没有好的处理方法啊

**Comment by H07000223** [comment]
没有什么好的办法~全部取出来，设置Visible.GONE
![image](https://cloud.githubusercontent.com/assets/3666423/24141015/f0f72256-0e5c-11e7-874e-983c83d5c90c.png)
