### ISSUE TITLE
请教个问题：STYLE设置为BLOCK时可以设置选中的BLOCK的颜色，但是如何设置未选中的BLOCK的颜色？

### ISSUE THREAD

**Issue by ningwy** [H07000223/FlycoTabLayout#136]
用的是SlidingTabLayout

**Comment by H07000223** [comment]
选中有色块，未选中没有~跟颜色没关系

**Comment by chuxiaokeAndroid** [comment]
未选中没有的话，就是设置不了吗？？？未选中背景颜色

**Comment by haoguibao** [comment]
> 未选中没有的话，就是设置不了吗？？？未选中背景颜色

各位大哥，未选中的背景色你们最终是怎么添加的，换了个其它的开源项目，还是自定义修改了一下呢？

**Comment by haoguibao** [comment]
> 用的是SlidingTabLayout
各位大哥，未选中的背景色你们最终是怎么添加的，换了个其它的开源项目，还是自定义修改了一下呢？
