### ISSUE TITLE
v4与nineoldandroids引用冲突

### ISSUE THREAD

**Issue by weinierfei** [H07000223/FlycoTabLayout#15]
嗨您好,首先非常感谢您的开源库!我现在有个问题,我的项目中使用了您的库(com.flyco.tablayout:FlycoTabLayout_Lib:2.0.0@aar),我看您的项目中也引用了v4及nineoldandroids;我自己的项目中也引用了com.android.support:support-v4:23.2.1;考虑到与其他v4版本的兼容问题,您看您的库中的v4及nineoldandroids能不能只引用不打包!谢谢

**Comment by H07000223** [comment]
本来就是如此...
