### ISSUE TITLE
首页底部多个tab点击无反应

### ISSUE THREAD

**Issue by yangyiRunning** [H07000223/FlycoTabLayout#152]
代码如下：
       mMainTabLayout.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelect(int position) {
                mMainViewPager.setCurrentItem(position);
            }
            @Override
            public void onTabReselect(int position) {

            }
        });

已经给tablayout安置了点击的监听事件，但是戳屏幕的tab并不触发，求解一下……3Q

**Comment by yangyiRunning** [comment]
已经解决，事件被父视图拦截……

**Comment by a362310485** [comment]
请问怎么解决的？
