### ISSUE TITLE
请教一下，如何实现出类似闲鱼那种中间有一个突起按钮的效果

### ISSUE THREAD

**Issue by lmyDevs** [H07000223/FlycoTabLayout#156]
如何实现出类似闲鱼那种中间有一个突起按钮的效果，并且没有viewpager滑动时的选中状态，就是中间突起的这个按钮不和viewpager绑定

**Comment by playscforever** [comment]
@lmyDevs 你搞定了吗

**Comment by lmyDevs** [comment]
@playscforever 搞定了，只不过用的不是这个框架

**Comment by playscforever** [comment]
@lmyDevs 哇塞  指导一下呗
我现在的方案是在这个基础之上加一个FloatingActionButton

**Comment by lmyDevs** [comment]
@playscforever JPTabBar 我用的这个，但是这个库写的不够好，如果你项目中用的是宏洋的AutoLayout的话，会出问题
