### ISSUE TITLE
如何动态改变Tab数目

### ISSUE THREAD

**Issue by AegisLee** [H07000223/FlycoTabLayout#16]
indicator无法跟着动态变, 必须要手动切换下才行;

**Comment by H07000223** [comment]
SlidingTablayout的话,试试重新调用setViewPager(ViewPager vp, String[] titles)
其他TabLayout也类似,试试setTabData(ArrayList<CustomTabEntity> tabEntitys)方法

**Comment by AegisLee** [comment]
我得做法就是重新初始化, 但是indicator并未及时更新重绘, 必须在进行了Tab页面切换后,indicator的宽度和位置才会正常,

**Comment by H07000223** [comment]
用的是那种Tablayout我试下~

**Comment by kingslou** [comment]
然后呢，朋友，这个问题有解决方案了吗？
重新初始化, 但是indicator宽度和位置并未及时更新重绘, 必须在进行了Tab页面切换后,indicator的宽度和位置才会正常,
