### ISSUE TITLE
横屏切换为竖屏导致Fragments重叠

### ISSUE THREAD

**Issue by zongren** [H07000223/FlycoTabLayout#17]
1. 第一次打开页面是这样的

![screenshot_2016-04-28-16-10-58](https://cloud.githubusercontent.com/assets/4525819/14879448/eef36c56-0d5b-11e6-9fe7-5076dc35050c.png)

2. 切换横屏、竖屏若干次后是这样的

![screenshot_2016-04-28-16-10-45](https://cloud.githubusercontent.com/assets/4525819/14879449/eef9706a-0d5b-11e6-90b6-5321e296418a.png)

**Comment by zongren** [comment]
如果Fragments没有设置背景色的话，就会出现重叠的现象
______________________________________________
![screenshot_2016-04-28-16-14-36](https://cloud.githubusercontent.com/assets/4525819/14879542/6260fac8-0d5c-11e6-86dd-2e602c811ffd.png)

**Comment by H07000223** [comment]
嗯~横竖屏切换没考虑~这边没处理
使用setTabData(ArrayList<CustomTabEntity> tabEntitys)方法吧,不要使用那个快捷方法~
然后google下,自己处理😂

**Comment by zongren** [comment]
问题不大，反正不支持横屏 😄

**Comment by H07000223** [comment]
嗯~这个需要的话~自己单独处理~😄

**Comment by Christain** [comment]
您好，我也遇到了这个问题，我的是Activity被回收以后会出现重叠的情况，当然横竖屏切换也会引起Activity重新加载。我已经通过onSaveInstanceState这个方法保存了tabLayout.getCurrentTab()当前页面的编号，在恢复的onCreate里面tabLayout.setCurrentTab(currentTab);指定了当前页面。但还是出现了重叠现象，这一点感到很困惑。

**Comment by H07000223** [comment]
tabLayout自己就记录了currentTab~ 你不需要再保存~
重叠的原因,说明fragment并没有被销毁,可能要解决的问题是如何重新再找到没有被销毁的当前fragment.而不是重新创建fragment

**Comment by zongren** [comment]
我把show，hide改成了replace暂时解决了这个问题
