### ISSUE TITLE
how to dynamic update slidingTalayout when adpter notifydatasetchanged

### ISSUE THREAD

**Issue by foreverxiongtao** [H07000223/FlycoTabLayout#18]

**Comment by H07000223** [comment]
more details

**Comment by zjc** [comment]
you can send event to update the tablayout in the MainActivity

**Comment by foreverxiongtao** [comment]
比如说viewpager的adapter的数量发生了变化，sldingtablayout的数量没有更新

**Comment by H07000223** [comment]
嗯~的确有这个问题~等我更新下个版本~顺利的话,可能在这周周末~最近比较忙😂

**Comment by foreverxiongtao** [comment]
辛苦了，调用slidingtablayout.setViewpager(viewpager)时，好像貌似里面的textview 选中的状态还是上一次的，并没有刷新，你可以留意一下

**Comment by H07000223** [comment]
slidingtablayout.setViewpager(viewpager)只在初始的时候用~关于更新的方法我下个版本进行修正

**Comment by H07000223** [comment]
更新到2.0.6了，你试一下，大致使用方式：
```java
mFragments.add(SimpleCardFragment.getInstance("title"));
mAdapter.notifyDataSetChanged();
tabLayout.addNewTab("后title");
```
