### ISSUE TITLE
Fragment 嵌套Fragment 里面用这个控件的BUG

### ISSUE THREAD

**Issue by Biswangluo** [H07000223/FlycoTabLayout#187]
![qq 20170706110930](https://user-images.githubusercontent.com/2362450/27893924-9dd78c86-623b-11e7-90de-04678d8ea19d.png)

改成这样就能在嵌套中使用不出问题了
![qq 20170706111039](https://user-images.githubusercontent.com/2362450/27893957-d7366c36-623b-11e7-8608-49f479c6e9e2.png)

**Comment by c297131019** [comment]
试过了，也不行。已经放弃了，看来在同级别fragment中，不能出现两次这个库的控件，否则会出错

**Comment by stormlei** [comment]
我试了下，真的可以

**Comment by payne1107** [comment]
一个activity中每个fragment都有一个该库的控件会出错   这个怎么解决的
