### ISSUE TITLE
SegmentTabLayout  如果超过屏幕宽度  

### ISSUE THREAD

**Issue by Cornflower1991** [H07000223/FlycoTabLayout#20]
我想换行  我改了下存放 Textview的容器 发现内容是换的 但是 背景呀 整体还是没有换  draw 里边的代码有点没读懂 不太好改

**Comment by H07000223** [comment]
上张效果图~我看能不能实现

**Comment by Cornflower1991** [comment]
![image](https://cloud.githubusercontent.com/assets/12163469/15539080/f147ef9c-22b2-11e6-9b2e-e6fb7c238b6c.png)

**Comment by H07000223** [comment]
1.两排不支持啊~虽然可以改~但是不如自己xml布局来的快~
2.也可以尝试TableLayout或者GridLayout
