### ISSUE TITLE
华为P9使用SlidingTabLayout字数是4个的时候会显示省略号

### ISSUE THREAD

**Issue by Cashdispenser** [H07000223/FlycoTabLayout#200]
![191055780451081083](https://user-images.githubusercontent.com/26020575/28651793-89902568-72b6-11e7-939e-3bca30551f07.jpg)

**Comment by tmxd09887** [comment]
我也遇到了，字数多的时候，出现省略号。中文还好办，字数少，可以设置固定宽度。英文字数多，就很麻烦。

看了tab textview

<TextView
        android:id="@+id/tv_tab_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:gravity="center"
        android:singleLine="true"/>

wrap_content应该不会省略啊
