### ISSUE TITLE
你好,标题能不能换行呢?加了\n好像没用呢

### ISSUE THREAD

**Issue by JamesLebron** [H07000223/FlycoTabLayout#22]
如何所示,能不能像这样换行呢?
![f k e8ba8bzy k x84 wg](https://cloud.githubusercontent.com/assets/12559144/15701727/aafcefae-280e-11e6-9d59-813a3e60dd8b.png)

**Comment by javake** [comment]
你这方向不好，要去动布局， CustomTabEntity 里增加负标题方法，然后布局也适配。

**Comment by H07000223** [comment]
for (int i = 0; i < tabcount; i++) {
            tabLayout.getTitleView(i).setSingleLine(false);
  }

如果ui显示不下~在布局里设置tl_tab_padding为0

**Comment by IT-Talon** [comment]
弄两个tablayout联动就好了，动态更新数值可以通过 sts2.getTitleView(0).setText(111); sts2.getTitleView(1).setText(222);
