### ISSUE TITLE
MsgView 在Tab 数量为2个时 未读消息偏移变成在文字的左上角问题

### ISSUE THREAD

**Issue by star95** [H07000223/FlycoTabLayout#24]
在demo 上修Tab 数量为2 就可以发现问题了
 tabLayout.showMsg(1, 5);
 tabLayout.setMsgMargin(1, 5, 10);
xml is
 <com.flyco.tablayout.SlidingTabLayout
        android:id="@+id/tablayout"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        android:background="@android:color/white"
        android:paddingLeft="16dp"
        android:paddingRight="16dp"
        tl:tl_textsize="@dimen/text_size_14"
        tl:tl_indicator_color="#489DF3"
        tl:tl_indicator_height="3dp"
        tl:tl_indicator_width_equal_title="false"
        tl:tl_tab_padding="22dp"
        tl:tl_tab_space_equal="true"
        tl:tl_textSelectColor="#000000"
        tl:tl_textUnselectColor="#66000000"/>

**Comment by H07000223** [comment]
参考[#issue4](https://github.com/H07000223/FlycoTabLayout/issues/4)
补充：
方式1：代码设置TabWidth（注意方法参数单位是dp）
```java
        int tabCount = 2;
        DisplayMetrics dm = getResources().getDisplayMetrics();
        float tabWidth = dm.widthPixels / dm.density / tabCount;
        tabLayout_2.setTabWidth(tabWidth);
        tabLayout_2.setTabPadding(0);//默认20dp,去除尽量防止出现文字省略号的情况
        tabLayout_2.showMsg(1, 5);
        tabLayout_2.setMsgMargin(1, 5, 10);
```

方式2：代码设置setMsgMargin(同样注意单位dp)
```java
        int tabCount = 2;
        DisplayMetrics dm = getResources().getDisplayMetrics();
        tabLayout_2.setTabPadding(0);//默认20dp,去除尽量防止出现文字省略号的情况
        tabLayout_2.showMsg(1, 5);
        tabLayout_2.setMsgMargin(1, dm.widthPixels / dm.density / tabCount / 2 + 5, 10);
```
