### ISSUE TITLE
属性不起作用

### ISSUE THREAD

**Issue by bdyz1016** [H07000223/FlycoTabLayout#26]
字体颜色和下划线永远都是白色，设置的颜色不起作用

**Comment by yaochangliang159** [comment]
我也碰到这个问题了，，，好奇怪。。但是在别的界面是好的，就这一个界面，有问题，好奇怪啊

**Comment by yaochangliang159** [comment]
已解决，在xml中注意要有这句话！！！！
 xmlns:tl="http://schemas.android.com/apk/res-auto"
我的之前是
 xmlns:tl="http://schemas.android.com"
当然不起作用了
