### ISSUE TITLE
SlidingTabLayout 问题

### ISSUE THREAD

**Issue by 598588152** [H07000223/FlycoTabLayout#277]
用SlidingTabLayout: +ViewPager   第一次进入页面，加载Fragment正常，退出，再次进入，加载不出来Fragment

**Comment by 598588152** [comment]
在Fragment中添加的

**Comment by 598588152** [comment]
找到问题了 引用错了getSupportFragmentManager 改成 getChildFragmentManager();

**Comment by Iamrookie** [comment]
SlidingTabLayout、CommonTabLayout  的tab中的text不显示  找不到原因   demo是可以，是有什么要注意的问题吗
