### ISSUE TITLE
Tab中的文字text不显示

### ISSUE THREAD

**Issue by Iamrookie** [H07000223/FlycoTabLayout#279]
试过SlidingTabLayout、CommonTabLayout  的tab中的text不显示  找不到原因   demo是可以，是有什么要注意的问题吗   但是跟demo弄的一样哇，囧

**Comment by xiaobei56** [comment]
为啥 closed啊，我也不显示，啥原因啊

**Comment by Kenmmm** [comment]
我这也不显示。。。。。只有SegmentTabLayout标题是显示的。。。
