### ISSUE TITLE
mTabLayout.setTabData(mTabEntities);总是报空指针为什么呀？求解。谢谢

### ISSUE THREAD

**Issue by BaiMingxu** [H07000223/FlycoTabLayout#284]
NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

**Comment by hanouba** [comment]
遇到同样问题 求解

**Comment by hanouba** [comment]
getLayout 方法写的位置错误导致的
