### ISSUE TITLE
切换的时候如何动态改变title文字的大小，比如选中的tab文字要比其它的大一点！

### ISSUE THREAD

**Issue by MIkeeJY** [H07000223/FlycoTabLayout#29]
用的slidingTab

**Comment by H07000223** [comment]
暂时没支持~需要你自己改造下

**Comment by MIkeeJY** [comment]
@H07000223  private void updateTabSelection(int position) {
        for (int i = 0; i < mTabCount; ++i) {
            View tabView = mTabsContainer.getChildAt(i);
            final boolean isSelect = i == position;
            TextView tab_title = (TextView) tabView.findViewById(R.id.tv_tab_title);

            if (tab_title != null) {
                tab_title.setTextColor(isSelect ? mTextSelectColor : mTextUnselectColor);
                //TODO
                if (isSelect) {
                    tab_title.setTextSize(TypedValue.COMPLEX_UNIT_PX, sp2px(19));
                } else {
                    tab_title.setTextSize(TypedValue.COMPLEX_UNIT_PX, sp2px(17));
                }
            }
        }
    }
这个方法可以改造成动态的 我这里只写死了

**Comment by amosxb** [comment]
谢谢这位兄弟提供的思路
