### ISSUE TITLE
关于tab点击的建议

### ISSUE THREAD

**Issue by liao10108180** [H07000223/FlycoTabLayout#31]
大神你好，我最近做项目用到了你的Tab，但是有一点瑕疵，当viewpage里有多个页面，tab中点击到某个界面时候，需要滑过中途的界面。
希望大神能够增加viewpager.setCurrentItem(int item, boolean smoothScroll)这个方法。
期待改进

**Comment by MIkeeJY** [comment]
这个自己在代码里设置就好咯~

**Comment by yangqb** [comment]
请问这个是在tab点击监听设置吗？，我这个设置后还是会中途划过很多页面。
 slidingTabLayout.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelect(int position) {
                mViewPager.setCurrentItem(position, false);
            }

            @Override
            public void onTabReselect(int position) {
            }
        });
