### ISSUE TITLE
setViewPager(ViewPager vp, String[] titles)能否删除titles必须非空的校验？

### ISSUE THREAD

**Issue by ancode-cn** [H07000223/FlycoTabLayout#33]
我们的Tab数据是动态的，当Tab数据为空时，需要清空页面上的Tab

**Comment by H07000223** [comment]
你可以传空数组

**Comment by H07000223** [comment]
不校验的~代码好多地方都会报错~
这个你应该可以自己处理，Tab数据为空的时候~可以不调用TabLayout相关方法，并隐藏他。
不要公用一个Tab数据源就可以了
