### ISSUE TITLE
设置tl:tl_tab_space_equal="true"，未读消息位置错误

### ISSUE THREAD

**Issue by ancode-cn** [H07000223/FlycoTabLayout#34]
![image](https://cloud.githubusercontent.com/assets/9337789/17044918/1050c258-4ff7-11e6-82a6-154dce3a1ca1.png)

**Comment by H07000223** [comment]
参考[#issue24](https://github.com/H07000223/FlycoTabLayout/issues/24)
参考[#issue4](https://github.com/H07000223/FlycoTabLayout/issues/4)
