### ISSUE TITLE
viewpager的滑动 与 Tab的点击 是否可以分离 

### ISSUE THREAD

**Issue by yyf1994** [H07000223/FlycoTabLayout#35]
作者，请教个问题，现在是点击tab时默认滑动了viewpager,我想实现一个功能是 点击tab和滑动viewpager时得到的数据不同，请问应该怎么实现？

**Comment by H07000223** [comment]
点击tab和滑动viewpager的数据不同是神马意思
你可以使用CommonTabLayout那个是分离的

**Comment by yyf1994** [comment]
我现在有个需求，是点击底部菜单的时候显示所有的，然后滑动的时候显示查询出来的数据，不知道能不能实现

**Comment by H07000223** [comment]
这么变态的需求。。。
你可以尝试下在tab点击监听事件记录点击状态，false的话就认为滑动，设置不同的数据源

**Comment by yyf1994** [comment]
好的，谢谢

**Comment by yyf1994** [comment]
tab点击的时候设置为true,那什么情况下在设置为false呢？点击之后默认也滑动了viewpager

**Comment by yyf1994** [comment]
不好意思，解决了，根据手势判断的
