### ISSUE TITLE
在fragment中使用遇到了无法显示SlidingTabLayout的布局  

### ISSUE THREAD

**Issue by yinking1203** [H07000223/FlycoTabLayout#360]
在fragment中使用遇到了无法显示SlidingTabLayout的布局   无法找到原因

**Comment by benpaobadaima** [comment]
SlidingTabLayout中默认用的是fragmentManager管理器，如果fragment嵌套的话，得继SlidingTabLayout，然后自己写个adapter，把里面的fragmentManager换成childFragmentManager就ok了

**Comment by TopTime1** [comment]
j解决了吗？

**Comment by yinking1203** [comment]
> Ĵ解决了吗？

解决了

**Comment by TopTime1** [comment]
怎么解决的？
