### ISSUE TITLE
如果设置tab充满屏幕（tl:tl_tab_space_equal="true"），然后showDot，红点位置不对

### ISSUE THREAD

**Issue by chenli3238** [H07000223/FlycoTabLayout#4]
bug，建议快点修改

**Comment by chenli3238** [comment]
正常情况应居于tab右上方，目前是不对的

**Comment by H07000223** [comment]
对于SlidingTab的话,tl:tl_tab_space_equal="true"并不能100%保证平分.这种情况下红点的位置也不好计算
建议使用以下方式实现同样效果(假设5个Tab,总长度为屏宽):
tabLayout.setTabWidth(screenWidth/5)
tabLayout.setPadding(0)//默认20dp,去除尽量防止出现文字省略号的情况

顺便试试红点位置对不对
