### ISSUE TITLE
添加3个fragment 时，则无法显是数据

### ISSUE THREAD

**Issue by caoanqi** [H07000223/FlycoTabLayout#41]
fragment 添加到3个以上是，无法显示里面的数据，调试发现第三个fragment 的oncreate 没有执行，不知为什么？
两个fragment 是可以正常显示数据？
谢谢!
简单贴下使用代码：
activity：
    public void initPager() {

        mFragments.add(PIMemberFragment.getInstance());
        mFragments.add(PIContactUnitFragment.getInstance());
        mFragments.add(PIAttachmentsFragment.getInstance());

        mSlidingTabLayout.setViewPager(mViewPager, mTitles, this, mFragments);
        mViewPager.setCurrentItem(0);
    }
fragment： 

    public static synchronized PIAttachmentsFragment getInstance() {
        if (piAttachmentsFragment == null)
            piAttachmentsFragment = new PIAttachmentsFragment();
        return piAttachmentsFragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        piAttachmentsFragment = this;
    }

    @Override
    public View onCreateView(LayoutInflater inflater,
                             ViewGroup container,
                             Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.fragment_related_attachments, null);
        ll_home_attachments = (LinearLayout) v.findViewById(R.id.ll_home_attachments);

        return v;
    }

**Comment by H07000223** [comment]
1.三页的话，可以尝试mPager.setOffscreenPageLimit(2)，默认是1
2. 带有fragment参数的setViewPager方法有问题的话，可以自行处理，在绑定viewpager

**Comment by caoanqi** [comment]
添加mPager.setOffscreenPageLimit(2)，也不可以啊

有自定义数据添加，代码如下：
    public void setData(List<RelatedAttachmentsInfo> relatedAttachmentsInfos) {
        try {

            if (relatedAttachmentsInfos.size() > 0) {
                for (RelatedAttachmentsInfo relatedAttachmentsInfo : relatedAttachmentsInfos) {
                    TabAttachmentsView tabAttachmentsView = new TabAttachmentsView(this.getActivity(), relatedAttachmentsInfo);
                    ll_home_attachments.addView(tabAttachmentsView);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

谢谢！

**Comment by caoanqi** [comment]
ok，过程虽然曲折 ，但解决了。
感谢

**Comment by caoanqi** [comment]
![30](https://cloud.githubusercontent.com/assets/3326826/17364156/33cd01a6-59b1-11e6-925e-289769453a9a.jpg)

这里没有数据时，切换位置不对？有什么需要特别设置？有数据 是正常的。
谢谢
