### ISSUE TITLE
迁移AndroidX

### ISSUE THREAD

**Issue by 979881765** [H07000223/FlycoTabLayout#437]
希望能适配android x

**Comment by getglory** [comment]
> 希望能适配android x

作者已经3年没维护了 还是下载下来自己改吧

**Comment by relish-wang** [comment]
由于大家对于AndroidX的呼声越来越高，而作者又长期不更新。
本人fork了此仓库([relish-wang/FlycoTabLayout](https://github.com/relish-wang/relish-wang/FlycoTabLayout))并在jcenter上发布了支持AndroidX的新版本(v3.0.0)。
```groovy
implementation 'com.flyco.tablayout:FlycoTabLayout_Lib:3.0.0'
```
但由于我无法发布到中央仓库(与原作者的依赖坐标重复; 没有修改坐标也是为了尊重原作), 所以如果你需要使用支持AndroidX的新版本(v3.0.0)还需要在你工程根目录下的`build.gradle`的`allprojects`节点下的`repositories`节点中添加这行代码):
```groovy
maven { url "https://dl.bintray.com/relish-wang/maven/" }
```
像这样:
```groovy
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://dl.bintray.com/relish-wang/maven/" } // 添加这行
    }
}
```
这样你就完成了对FlycoTabLayout_Lib的AndroidX改造。

**Comment by pumatus** [comment]
适配androidX 多简单  ，把此框架的support改成androix的就可以了运行了

**Comment by oudengding** [comment]
viewpager滑动卡顿怎么怎么回事？

**Comment by doulemint** [comment]
> 由于大家对于AndroidX的呼声越来越高，而作者又长期不更新。
> 本人fork了此仓库([relish-wang/FlycoTabLayout](https://github.com/relish-wang/FlycoTabLayout))并在jcenter上发布了支持AndroidX的新版本(v3.0.0)。
> 
> ```groovy
> implementation 'com.flyco.tablayout:FlycoTabLayout_Lib:3.0.0'
> ```
> 
> 但由于我无法发布到中央仓库(与原作者的依赖坐标重复; 没有修改坐标也是为了尊重原作), 所以如果你需要使用支持AndroidX的新版本(v3.0.0)还需要在你工程根目录下的`build.gradle`的`allprojects`节点下的`repositories`节点中添加这行代码):
> 
> ```groovy
> maven { url "https://dl.bintray.com/relish-wang/maven/" }
> ```
> 
> 像这样:
> 
> ```groovy
> buildscript {
>     repositories {
>         google()
>         jcenter()
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.4.2'
>     }
> }
> 
> allprojects {
>     repositories {
>         google()
>         jcenter()
>         maven { url "https://dl.bintray.com/relish-wang/maven/" } // 添加这行
>     }
> }
> ```
> 
> 这样你就完成了对FlycoTabLayout_Lib的AndroidX改造。

我这没有import不了slidingTabLayout
