### ISSUE TITLE
CommonTabLayout 如何自动选择第一个选项卡呢

### ISSUE THREAD

**Issue by tianshaokai** [H07000223/FlycoTabLayout#45]

**Comment by H07000223** [comment]
。。。难道不是默认😂

**Comment by tianshaokai** [comment]
@H07000223  我当时理解错了，我在CommonTabLayout  切换fragment, 想默认选择第一个fragment, 当时想着如何设置CommonTabLayout  默认选择第一个，后来修改了实现方式
