### ISSUE TITLE
建议兼容AndroidX

### ISSUE THREAD

**Issue by lzjin** [H07000223/FlycoTabLayout#457]
建议兼容AndroidX

**Comment by liudaohong** [comment]
我也在转AndroidX 好麻烦 有四个库都还没有更新AndroidX

**Comment by Chenjiabin09** [comment]
+1

**Comment by OneTake1998** [comment]
+1

**Comment by HirayClay** [comment]
配置一下 enableJetifier = true ，编译时候，AS 是会替换掉依赖的，比如 依赖的是 v4 的 Fragment ,都会依赖 androidx ，迁移之后项目还是可以跑起来的
