### ISSUE TITLE
有关禁止tablayout停止滑动的问题

### ISSUE THREAD

**Issue by liao10108180** [H07000223/FlycoTabLayout#46]
大神你好，我现在项目有个需求，根据条件判断viewpager是否可以滑动，当viewpager禁止滑动后，tablayout还是会滑动，我想问下有没有禁止tablayout滑动的方法，如果没有在源码哪里改比较好？

**Comment by H07000223** [comment]
SlidingTabLayout是继承HorizontalScrollView，所以想办法禁止HorizontalScrollView的滚动就可以了
