### ISSUE TITLE
当tab选项为5个的时候，如果选项的字体等于或超过三个字的话，设置未读数两位数以上未读消息时，显示不完全

### ISSUE THREAD

**Issue by moselin** [H07000223/FlycoTabLayout#47]
当tab选项为5个的时候，如果选项的字体超过三个字的话，设置未读数两位数以上未读消息时，显示不完全

**Comment by H07000223** [comment]
嗯，用的是哪种Tab

**Comment by moselin** [comment]
用的是CommonTabLayout

**Comment by H07000223** [comment]
嗯~试了下~的确有这种问题~有时间的话修了这个bug
目前你可以下面方式暂时处理（间距不合适的话，手动慢慢调😂 ）
2位数  mTabLayout.setMsgMargin(0, -10, 5);
3位数  mTabLayout.setMsgMargin(0, -15, 5);
