### ISSUE TITLE
 CommonTabLayout 是否支持自定义tab呢

### ISSUE THREAD

**Issue by tianshaokai** [H07000223/FlycoTabLayout#48]
![image](https://cloud.githubusercontent.com/assets/6706496/17642413/1b126786-6178-11e6-9473-777373b5a353.png)

我的tab 是这样的，我自己写一个layout  怎样 设置到 CommonTabLayout  上呢

**Comment by H07000223** [comment]
把'标题(2)'整体当title处理~唯一要考虑的是标题中数字的颜色,可以试试ForegroundColorSpan

**Comment by tianshaokai** [comment]
@H07000223  嗯嗯 我去搜一下这个ForegroundColorSpan 资料
