### ISSUE TITLE
各种颜色设置没用。功能都正常，有人碰到锅吗？

### ISSUE THREAD

**Issue by devzwy** [H07000223/FlycoTabLayout#498]
？

**Comment by devzwy** [comment]
<img width="1210" alt="截屏2020-07-02 11 51 11" src="https://user-images.githubusercontent.com/24636051/86314470-58bbc280-bc5a-11ea-84cf-4925efcff9cc.png">

**Comment by lifeifeijack** [comment]
怎么解决的兄弟

**Comment by devzwy** [comment]
我估计是引入的这两个东西冲突，解决了颜色问题后发现滑动的时候跳。还没解决跳的问题。
```
xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
```
