### ISSUE TITLE
How to set up the border width or border color of indicator in SegmentTabLayout

### ISSUE THREAD

**Issue by HuJianChong** [H07000223/FlycoTabLayout#5]
SegmentTabLayout中， 如何设置indicator的边框宽度或者颜色

**Comment by H07000223** [comment]
对于SegmentTabLayout
tl_indicator_color          色块颜色
tl_bar_color                   背景条颜色
tl_bar_stroke_color       背景条边框颜色
tl_bar_stroke_width      背景条边框宽度

indicator色块默认高度为控件高度,宽度为Tab所占宽度.
可以通过设置tl_indicator_margin改变indicator宽高

具体参考Demo以及attrs.xml文件

**Comment by HuJianChong** [comment]
谢谢，看的时候看漏了，控件很nice~~
