### ISSUE TITLE
What's the license of the source code?

### ISSUE THREAD

**Issue by felixding** [H07000223/FlycoTabLayout#50]
Does the project have a specific license? Could't find it anywhere.

**Comment by H07000223** [comment]
MIT

![image](https://cloud.githubusercontent.com/assets/3666423/17723332/ebdcf0fc-646b-11e6-9c05-e4a477956be6.png)

**Comment by felixding** [comment]
MIT is great.

It's not in the readme (which is normal for OSS) so I didn't check the
source code. Thanks.
