### ISSUE TITLE
SlidingTabLayout 点击，viewpage设置了 viewpage.setCurrentItem(position, false);，还是会划过中间的界面

### ISSUE THREAD

**Issue by renwfy** [H07000223/FlycoTabLayout#53]
SlidingTabLayout 点击，
viewpage设置了 viewpage.setCurrentItem(position, false);，
还是会划过中间的界面，，

我看你代码里面，切换的时候。viewpage.setCurrentItem(position);，没有用第二个参数

**Comment by H07000223** [comment]
最新的库已经新增了一个方法
![image](https://cloud.githubusercontent.com/assets/3666423/17841835/59199c74-684f-11e6-8a7d-5fbc0002559f.png)
