### ISSUE TITLE
使用CommonTabLayout的时候，当给tab设置了OnTabSelectListener之后，indicator的bounce动画就消失了

### ISSUE THREAD

**Issue by brandlee** [H07000223/FlycoTabLayout#55]
代码如下：
mTabLayout.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelect(int i) {
                mViewPager.setCurrentItem(i);
            }
            @Override
            public void onTabReselect(int i) {
            }
        });

**Comment by H07000223** [comment]
额~在demo基础上试了下~是可以的...
```java
 mTabLayout_6.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelect(int position) {
                mViewPager.setCurrentItem(position);
            }

            @Override
            public void onTabReselect(int position) {
            }
        });
```

**Comment by brandlee** [comment]
我找到原因了，是onTabSelectListener和ViewPager的addOnPageChangeListener产生了循环调用

**Comment by Puppy-Love** [comment]
@brandlee 只监听一个滑动 监听滑动，点击view就不能切换，监听点击，滑动view tab也不能切换
