### ISSUE TITLE
大神，SlidingTabLayout能否像CommonTabLayout，单独提供一个加载标题数据的方法？

### ISSUE THREAD

**Issue by songj056** [H07000223/FlycoTabLayout#57]
SlidingTabLayout能否像CommonTabLayout，单独提供一个加载标题数据的方法？用起来能单独的setTabData(String[] titles)呢？我想结合RecyclerView直接改变数据。

**Comment by H07000223** [comment]
没太弄明白你的需求,但是SlidingTabLayout必须设置ViewPager.
如果你想CommonTablayou也支持滚动的话,可以尝试在最外层嵌套一个ScrollView

**Comment by songj056** [comment]
@H07000223 我的意思就是：SlidingTabLayout能否不要设置ViewPager，只设置titles

**Comment by H07000223** [comment]
不支持
