### ISSUE TITLE
"tl_indicator_width_equal_title" does not work.

### ISSUE THREAD

**Issue by newbeeeeeeeee** [H07000223/FlycoTabLayout#59]
I use “tl_indicator_width”, Indicator can be displayed, but the use of "tl_indicator_width_equal_title", will not show.

**Comment by H07000223** [comment]
...
show me the code

**Comment by newbeeeeeeeee** [comment]
`<com.flyco.tablayout.SlidingTabLayout
            android:id="@+id/tl_1"
            android:layout_width="match_parent"
            android:layout_height="40dp"
            app:tl_indicator_color="@color/colorAccentSecondary"
            app:tl_indicator_height="2dp"
            app:tl_indicator_gravity="BOTTOM"
            app:tl_indicator_style="NORMAL"
            app:tl_tab_space_equal="true"
            app:tl_underline_height="1dp"
            app:tl_underline_color="@color/lightGray"
            app:tl_underline_gravity="BOTTOM"
            app:tl_textSelectColor="@color/colorAccentSecondary"
            app:tl_textUnselectColor="@color/gray"
            app:tl_textsize="15sp"
            />`

**Comment by newbeeeeeeeee** [comment]
<com.flyco.tablayout.SlidingTabLayout
            android:id="@+id/tl_1"
            android:layout_width="match_parent"
            android:layout_height="40dp"
            app:tl_indicator_color="@color/colorAccentSecondary"
            app:tl_indicator_height="2dp"
            app:tl_indicator_gravity="BOTTOM"
            app:tl_indicator_style="NORMAL"
            app:tl_tab_space_equal="true"
            app:tl_underline_height="1dp"
            app:tl_underline_color="@color/lightGray"
            app:tl_underline_gravity="BOTTOM"
            app:tl_textSelectColor="@color/colorAccentSecondary"
            app:tl_textUnselectColor="@color/gray"
            app:tl_textsize="15sp"
            />

**Comment by H07000223** [comment]
SlidingTablayout or CommonTablayout

**Comment by tokki-stack** [comment]
Is there any way to change the color of unfocused tab?
Thanks
