### ISSUE TITLE
please update a proguard rules file

### ISSUE THREAD

**Issue by 551780457** [H07000223/FlycoTabLayout#6]
please update a proguard rules file

**Comment by tangdingyi** [comment]
能否提供方法，点击tab时，在去new 相应的Fragment。
初始化时，new 所有的Fragment有点影响性能

**Comment by H07000223** [comment]
1.CommonTabLayout, SegmentTabLayout支持的,只要不使用带Fragment相关参数的setTabData方法即可
SlidingTabLayout理论上也是可以情况同上(没试过)
2.单纯创建Fragment并不会影响性能,估计是你将耗时的操作放在创建相关的生命周期方法里面.
你应该尝试Fragment懒加载的方式.在需要的时候加载数据.
