### ISSUE TITLE
这个title 可以自适应文字宽度吗

### ISSUE THREAD

**Issue by wwdn** [H07000223/FlycoTabLayout#61]
在用的时候，tab的宽度是可以指定的（每一个宽度都是一样的），可以自适应文字的宽度吗？2个文字显示2个文字的宽度，4个文字显示4个文字的宽度

**Comment by H07000223** [comment]
哪个TabLayout~应该可以~

**Comment by wwdn** [comment]
请问是哪一个呢？ 主要我用的是您这个带Indicator 下划线的 SlidingTabLayout

**Comment by H07000223** [comment]
不用设置tab宽度,默认应该就是可以的~

**Comment by liweijian2016** [comment]
是的,6.0以下的可以,但是6.0以上的就不行了,会出现省略号.很是尴尬,怎么解决.

**Comment by H07000223** [comment]
试试设置tabPadding为0，或者比较小的数

**Comment by DzwsGo** [comment]
鸿蒙4.0 会出现省略号
