### ISSUE TITLE
SlidingTabLayout  mTabSpaceEqual属性开启后无法滚动

### ISSUE THREAD

**Issue by Sabirjan** [H07000223/FlycoTabLayout#62]
这个mTabSpaceEqual属性开启后无法滚动，PagerSlidingTabStrip是可以的，但是不知道你的代码哪儿的问题，无法滚动。。。。超出页面的部分压缩一个页面上....应该滚动才对吧。。。。

好像layout的问题，我替换了一个textview就可以了，但是换layout不行

**Comment by Sabirjan** [comment]
比如一个新闻客户端，不一定所有tab都放在一个页面上啊....我的就是新闻客户端，类别有十几个，谢谢

**Comment by H07000223** [comment]
mTabSpaceEqual不设置true就好了~你希望每个tab宽度都一样,可以设置tl_tab_width

**Comment by Sabirjan** [comment]
我还是选别的吧，谢谢！不设置，如果两三条有点难看.....
