### ISSUE TITLE
动态设置SlidingTabLayout.setTabSpaceEqual (true)等分无效

### ISSUE THREAD

**Issue by huyanghu** [H07000223/FlycoTabLayout#66]

**Comment by H07000223** [comment]
可以通过设置tab宽度变相实现:
参考[#issue24](https://github.com/H07000223/FlycoTabLayout/issues/24)
参考[#issue4](https://github.com/H07000223/FlycoTabLayout/issues/4)

**Comment by huyanghu** [comment]
我通过修改源码解决了,解决方案如下:
 private void updateTabStyles() {
        for (int i = 0; i < mTabCount; i++) {
            View v = mTabsContainer.getChildAt(i);

//            v.setPadding((int) mTabPadding, v.getPaddingTop(), (int) mTabPadding, v.getPaddingBottom());
            TextView tv_tab_title = (TextView) v.findViewById(R.id.tv_tab_title);
            if (tv_tab_title != null) {
                tv_tab_title.setTextColor(i == mCurrentTab ? mTextSelectColor : mTextUnSelectColor);
                tv_tab_title.setTextSize(TypedValue.COMPLEX_UNIT_PX, mTextSize);
                tv_tab_title.setPadding((int) mTabPadding, 0, (int) mTabPadding, 0);
                if (mTextAllCaps) {
                    tv_tab_title.setText(tv_tab_title.getText().toString().toUpperCase());
                }

                if (mTextBold == TEXT_BOLD_BOTH) {
                    tv_tab_title.getPaint().setFakeBoldText(true);
                } else if (mTextBold == TEXT_BOLD_NONE) {
                    tv_tab_title.getPaint().setFakeBoldText(false);
                }
            }
// 增加如下代码就可以了
            if (mTabSpaceEqual) {
                v.setLayoutParams (new LinearLayout.LayoutParams (0, LayoutParams.MATCH_PARENT, 1.0f));

            } else {
                v.setLayoutParams (new LinearLayout.LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.MATCH_PARENT));
            }
            v.requestLayout ();
        }
    }
