### ISSUE TITLE
使用SlidingTabLayout，新打开Activity然后关闭，刷新当前页面，title不会切回

### ISSUE THREAD

**Issue by qzxing** [H07000223/FlycoTabLayout#70]
出现异常流程：
      在当前ActivityA中使用SlidingTabLayout——>切换到TAB2——>在当前ActivityA打开新的ActivityB——>关闭ActivityB——>刷新ActivityA——>这时TAB指示器和显示的都是是第一个，但是title确还是停留在第二个上面
表达能力不行，大概就是上面这样子

**Comment by H07000223** [comment]
应该是刷新ActivityA的姿势不对~
你先看看不刷新的话,会不会有这样的问题

**Comment by qzxing** [comment]
如果不刷新，我的ActivityA是没有finish的，所以显示的肯定是TAB2,不会有问题。不过不刷新我的界面数据是有变化的，所以要刷新。我的刷新操作是把所有的视图重新创建一遍（感觉确实有问题，不过能力有限） 我这里觉得就是指示器能回来到TAB1 title为什么不是一起回来呢

**Comment by H07000223** [comment]
试试刷新后~设置setCurrentTab呢

**Comment by qzxing** [comment]
设置setCurrentTab了需要设置两次，我现在就是这么用的 。
先setCurrentTab（1），再setCurrentTab（0）显示就没有问题

**Comment by H07000223** [comment]
估计是它的锅
![image](https://cloud.githubusercontent.com/assets/3666423/18978817/8f9f89b2-86f8-11e6-88d2-bee5f853098a.png)
