### ISSUE TITLE
指示器不显示

### ISSUE THREAD

**Issue by newbeeeeeeeee** [H07000223/FlycoTabLayout#73]
显示

![image of myTest](http://i.imgur.com/8vKEfN0.png)

代码

    <com.flyco.tablayout.SlidingTabLayout
            android:id="@+id/stlIndicator"
            android:layout_width="match_parent"
            android:layout_height="54dp"
            app:tl_indicator_color="@color/carouse_orange"
            app:tl_indicator_gravity="BOTTOM"
            app:tl_indicator_height="2dp"
            app:tl_indicator_style="NORMAL"
            app:tl_tab_space_equal="true"
            app:tl_indicator_width_equal_title="true"
            app:tl_textSelectColor="@color/black_light"
            app:tl_textUnselectColor="@color/gray"
            app:tl_textsize="16sp"
            app:tl_underline_color="@color/carouse_yellow"
            app:tl_underline_gravity="BOTTOM"
            app:tl_underline_height="1dp"
     />

**Comment by H07000223** [comment]
看下demo跑出来是不是也没有嘛

**Comment by newbeeeeeeeee** [comment]
demo也没有
机型原因么? 我的这个是模拟器

![demo](http://i.imgur.com/cCPHqpU.png)

**Comment by H07000223** [comment]
用相同的机型跑demo和你的项目啊~

**Comment by newbeeeeeeeee** [comment]
真机显示 , 有的模拟器不显示

**Comment by H07000223** [comment]
嗯~可能是分辨率过高~你把indicator高度设置大一点试试
