### ISSUE TITLE
底部使用CommonTabLayout(共4个按钮),子页面使用SegmentTabLayout(2个页面),一共8个页面,2,3,4底部对应的子页面出现覆盖

### ISSUE THREAD

**Issue by vipheyue** [H07000223/FlycoTabLayout#74]
底部使用CommonTabLayout(共4个按钮),子页面使用SegmentTabLayout(2个页面),一共8个页面,2,3,4底部对应的子页面出现覆盖,混在 一起了

**Comment by vipheyue** [comment]
如果 上面 底部对应的页面 只有一个页面有SegmentTabLayout 就一切正常,两个就会有问题

**Comment by H07000223** [comment]
1.检查下是不是用getChildFragmentManager()来获取fragmentManager
2.不要用自带的Fragment控制方法,自己写

**Comment by vipheyue** [comment]
恩,已经找到原因了.两个不同的Fragment 的布局里面 有一个 FrameLayout 的ID 都相同,导致的 后来我把其中一个布局中的FrameLayout 的ID 改了 ,就好了,,
你的开源挺好用的 有几个库我都在用

**Comment by H07000223** [comment]
😁
