### ISSUE TITLE
tab可以指定自己的View吗

### ISSUE THREAD

**Issue by renyanxu2000** [H07000223/FlycoTabLayout#75]
Tab能否换成自己的layout，我自己可以自定义这个tabview样式，动画等？

**Comment by H07000223** [comment]
暂不支持~较老的版本支持自定义的layout,动画暂时没有相关支持

**Comment by renyanxu2000** [comment]
@H07000223 Adapter要实现getCustomTabView吗？

**Comment by H07000223** [comment]
嗯~沿用老的PagerSlidingTrip,后来给我去了

**Comment by renyanxu2000** [comment]
哪个版本的可以支持自定义tab的layout，其实这个需求还是挺不错的

**Comment by H07000223** [comment]
估计一点几的版本~而且要额外引入一些库...

**Comment by renyanxu2000** [comment]
使用commonTabLayout，如果只有两个tab，我可以只设置第二个有icon吗？如果可以怎么弄

**Comment by H07000223** [comment]
其他tab图片资源填0?

**Comment by renyanxu2000** [comment]
填0 ，它还是占着位置

**Comment by H07000223** [comment]
那试试getTabView方法设置Visible Gone

**Comment by H07000223** [comment]
貌似可以用~不许用引入额外的库
![image](https://cloud.githubusercontent.com/assets/3666423/19345472/f91f3450-9170-11e6-8287-aac0e404102b.png)

**Comment by renyanxu2000** [comment]
getTabView方法在哪里？这个2.0.6版本是什么时候发布的，我引用的是2.0.0版本

**Comment by H07000223** [comment]
写错了,是getIconView
在changelog里面

**Comment by renyanxu2000** [comment]
tl_indicator_width 不能设置wrap_content?

**Comment by renyanxu2000** [comment]
tl_indicator_width_equal_title 也是适用commonTab更方便了

**Comment by sbwhy** [comment]
刚需你居然去除了

**Comment by hanchanpo13** [comment]
这么重要的功能 你居然去除了
