### ISSUE TITLE
设置了tablayout.setCurrentTab(currentIndex, false);但是不生效

### ISSUE THREAD

**Issue by weinierfei** [H07000223/FlycoTabLayout#78]
tablayout.setTabSpaceEqual(true);
        searchViewpaer.setOffscreenPageLimit(mFragmentList.size());
        searchViewpaer.setAdapter(new SearchPagerAdapter(getSupportFragmentManager()));
        tablayout.setViewPager(searchViewpaer, mTabs);
        tablayout.setCurrentTab(currentIndex, false);

版本:2.0.8;
设置了tablayout.setCurrentTab(currentIndex, false);但还是会划过中间界面,是我用的不对么?

**Comment by H07000223** [comment]
好像没有跳过中间的方法

**Comment by weinierfei** [comment]
那你看今日头条,凤凰新闻他们的那个,是怎么实现的

**Comment by H07000223** [comment]
我试了下~要改源码里面的
![image](https://cloud.githubusercontent.com/assets/3666423/19679010/c2b47ea0-9ad2-11e6-9e8d-29f2bec5251f.png)

**Comment by H07000223** [comment]
我试了下~要改源码里面的
![image](https://cloud.githubusercontent.com/assets/3666423/19679010/c2b47ea0-9ad2-11e6-9e8d-29f2bec5251f.png)

**Comment by weinierfei** [comment]
嗯哼;果然是这样的;那啥时候更新下呀,连同allowBackup和supportsRtl一起处理了呗

**Comment by H07000223** [comment]
等下个版本~我找个时间~

**Comment by H07000223** [comment]
修了~更新到2.1.0
