### ISSUE TITLE
when setCurrentTab(index) , the OnTabSelectListener() can not perform

### ISSUE THREAD

**Issue by chang-chaunce** [H07000223/FlycoTabLayout#8]
如题，当调用setCurrentTab(index)时，OnTabSelectListener() 不会执行。只有手动点击才会执行OnTabSelectListener()的监听。

**Comment by H07000223** [comment]
嗯,setCurrentTab只是做了些Ui更新~而OnTabSelectListener内部已经调用setCurrentTab(index).只是Tab点击事件对外提供回调接口
