### ISSUE TITLE
会有碎片窜屏 的现象

### ISSUE THREAD

**Issue by 385841539** [H07000223/FlycoTabLayout#90]
有的时候  卡顿一下 会有 碎片重叠 窜屏幕  的现象

**Comment by H07000223** [comment]
不用试用库中自带的FragmentTabManger，那个有点问题，自己整一个😂

**Comment by 385841539** [comment]
大神有没有写好的啊 ？  求赐教啊 。

**Comment by hanleirx** [comment]
求赐教  遇到了同样的问题

**Comment by 385841539** [comment]
你好 ， 这个问题很简单就解决了 ，  再activity里面 ， 要加个判断 ， 碎片相当于重复添加了 ， 你加我QQ385841539，验证荀彧 ， 郭嘉。 问题和答案顺序窝忘了

**Comment by H07000223** [comment]
可以参考下：
http://www.jianshu.com/p/d9143a92ad94
