### ISSUE TITLE
About CommonTabLayout

### ISSUE THREAD

**Issue by mm46468648** [H07000223/FlycoTabLayout#91]
CommonTabLayout虽然可以独立于viewpager,但是他只显示四个,多了并不能滑动
SlidingTablayout可以滑动,但是必须关联viewpager
我想要的是SlidingTablayout可以随意往里面添加tab,但是并不关联viewpgager可以么.

**Comment by H07000223** [comment]
commtablayout外面套一层HorizontalScrollView
