### ISSUE TITLE
How to use in styles.xml？

### ISSUE THREAD

**Issue by Andecy** [H07000223/FlycoTabLayout#94]
```xml
    <style name="MyTab">
        <item name="android:background">@color/white</item>
        <item name="com.flyco.tablayout:tl_indicator_color">@color/primary</item>
    </style>
```
or
```xml
<resources xmlns:tl="http://schemas.android.com/apk/res-auto">
    <style name="MyTab">
        <item name="android:background">@color/white</item>
        <item name="tl:tl_indicator_color">@color/primary</item>
    </style>
</resources>
```
are all build failed and messages are "Error:(2682, 21) No resource found that matches the given name: attr 'com.flyco.tablayout:tl_indicator_color'." or "Error:(2682, 21) No resource found that matches the given name: attr 'tl:tl_indicator_color'."

```gradle
    compile 'com.flyco.tablayout:FlycoTabLayout_Lib:2.1.0@aar'
```

**Comment by H07000223** [comment]
There is no support for style.xml 😂

**Comment by Andecy** [comment]
alright...well:joy::joy::joy:,

have any suggestion for using a common-style in many files?

**Comment by H07000223** [comment]
you may use <merge/> or <include/> label instead

**Comment by Andecy** [comment]
thank u,
