### ISSUE TITLE
如何设置两个tab之间的距离

### ISSUE THREAD

**Issue by Bobyang912** [H07000223/FlycoTabLayout#99]
当tl_tab_space_equal=true时，只有两个tab,如何设置tab之间的距离，默认的距离太大了

**Comment by H07000223** [comment]
TabLayout宽度设置为wrap_content，然后让TabLayout居中显示
这可以通过tabPadding属性调整间距

**Comment by Bobyang912** [comment]
谢谢，你这个方法也可以，之前设置宽度为match_parent，设置tabPadding为负值都不行，后来通过设置marginLeft和marginRight也能实现
